#mybatis:
#    codegen:
#        enabled: false
#        parent_pck: fit.wenchao.second_hand_trading_platform_front
#        author: wc
#        db_url: jdbc:mysql://localhost:3306/second_hand_trading_platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#        db_username: root
#        db_password: wc123456

spring:
    #???????
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource            # ?????????
        driver-class-name: com.mysql.cj.jdbc.Driver           # mysql???
        url: jdbc:mysql://localhost:3306/second_hand_trading_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: wc123456

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl